[[main]]
name = "انجمن"
weight = 20
url = "https://community.letsencrypt.org/"
[[main]]
name = "حمایت مالی"
weight = 30
identifier = "donate"
url = "/fa/donate/"
[[main]]
name = "درباره ما"
weight = 40
identifier = "about"
url = "/fa/about/"
[[main]]
name = "گروه تحقیقاتی امنیت اینترنت (ISRG)"
weight = 20
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"
[[main]]
name = "مشاهده وضعیت سرویس"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"
[[main]]
name = "فرصت های شغلی"
weight = 80
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"
